const { Property } = require("../models");

const propertyData = [
  {
    address_line1: "2301 A Knowles Ave,",
    address_line2: "",
    city: "Nashville",
    state: "TN",
    zip_code: "37204",
    county: "Davidson",
    property_type_id: 1, //'duplex',
    bedrooms: 4,
    bathrooms: 4,
    sq_ft: 2000,
    rent: 3000.0,
  },
  {
    address_line1: "2301 B Knowles Ave,",
    address_line2: "",
    city: "Nashville",
    state: "TN",
    zip_code: "37204",
    county: "Davidson",
    property_type_id: 1, //'duplex',
    bedrooms: 2,
    bathrooms: 2,
    sq_ft: 1500,
    rent: 2500.0,
  },
  {
    address_line1: "2303 A Knowles Ave,",
    address_line2: "",
    city: "Nashville",
    state: "TN",
    zip_code: "37204",
    county: "Davidson",
    property_type_id: 1, //'duplex',
    bedrooms: 2,
    bathrooms: 2,
    sq_ft: 1800,
    rent: 2200.0,
  },
  {
    address_line1: "2303 B Knowles Ave,",
    address_line2: "",
    city: "Nashville",
    state: "TN",
    zip_code: "37204",
    county: "Davidson",
    property_type_id: 1, //'duplex',
    bedrooms: 3,
    bathrooms: 2.5,
    sq_ft: 2500,
    rent: 2400.0,
  },
  {
    address_line1: "906 A Gale Ln",
    address_line2: "",
    city: "Nashville",
    state: "TN",
    zip_code: "37204",
    county: "Davidson",
    property_type_id: 1, //'duplex',
    bedrooms: 4,
    bathrooms: 4,
    sq_ft: 2000,
    rent: 3400.0,
  },
  {
    address_line1: "906 B Gale Ln",
    address_line2: "",
    city: "Nashville",
    state: "TN",
    zip_code: "37204",
    county: "Davidson",
    property_type_id: 1, //'duplex',
    bedrooms: 3,
    bathrooms: 3.5,
    sq_ft: 3000,
    rent: 4200.0,
  },
];

const seedProperties = () => Property.bulkCreate(propertyData);

module.exports = seedProperties;
